#!/usr/bin/env python3
"""NFS server 管理 CLI。本机运行；apply/status 通过 SSH 落到 115。"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore[assignment]

ROOT = Path(__file__).resolve().parent
CONFIG = ROOT / "config" / "users.yaml"
CRED_FILE = ROOT.parent / "115ssh"


def load_nfs_config() -> dict:
    if yaml is None:
        raise SystemExit("PyYAML required (use conda env serverA: pip already installed it)")
    with CONFIG.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def render_exports(cfg: dict) -> str:
    cidr = cfg["allowed_cidr"]
    opts = cfg["mount_options"]
    lines = [
        "# generated by 149server/nfsserver/nfsctl.py — do not edit on 115 by hand",
        f"{cfg['export_root']} {cidr}({opts})",
    ]
    for _name, body in (cfg.get("users") or {}).items():
        lines.append(f"{body['export_path']} {cidr}({opts})")
    return "\n".join(lines) + "\n"


def read_ssh_creds() -> tuple[str, str, str]:
    if not CRED_FILE.is_file():
        raise SystemExit(f"missing {CRED_FILE}")
    data: dict[str, str] = {}
    for line in CRED_FILE.read_text(encoding="utf-8").splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        data[key.strip().lower()] = value.strip()
    user = data.get("user") or os.environ.get("NFS_SSH_USER", "kairan")
    host = data.get("ip") or cfg_host_fallback()
    password = data.get("passwd") or os.environ.get("NFS_SSH_PASS", "")
    if not password:
        raise SystemExit("115 ssh password not found (115ssh or NFS_SSH_PASS)")
    return user, host, password


def cfg_host_fallback() -> str:
    try:
        return str(load_nfs_config()["nfs_host"])
    except Exception:
        return "10.250.30.115"


def sshpass_bin() -> str:
    candidate = Path.home() / "miniconda3" / "bin" / "sshpass"
    if candidate.is_file():
        return str(candidate)
    return "sshpass"


def ssh_run(remote: str) -> subprocess.CompletedProcess[str]:
    user, host, password = read_ssh_creds()
    env = os.environ.copy()
    env["SSHPASS"] = password
    cmd = [
        sshpass_bin(),
        "-e",
        "ssh",
        "-o",
        "PreferredAuthentications=password",
        "-o",
        "PubkeyAuthentication=no",
        "-o",
        "StrictHostKeyChecking=accept-new",
        f"{user}@{host}",
        remote,
    ]
    return subprocess.run(cmd, env=env, text=True, capture_output=True, check=False)


def cmd_render(_: argparse.Namespace) -> int:
    sys.stdout.write(render_exports(load_nfs_config()))
    return 0


def cmd_showmount(_: argparse.Namespace) -> int:
    cfg = load_nfs_config()
    proc = subprocess.run(["showmount", "-e", cfg["nfs_host"]], text=True)
    return proc.returncode


def cmd_status(_: argparse.Namespace) -> int:
    proc = ssh_run(
        "echo '=== exportfs -v ==='; sudo exportfs -v; "
        "echo '=== dirs ==='; ls -ld /mnt/dockerContainer/nfs /mnt/dockerContainer/nfs/*; "
        "echo '=== nfs-server ==='; systemctl is-active nfs-server"
    )
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    return proc.returncode


def apply_script(cfg: dict) -> str:
    exports = render_exports(cfg)
    mkdir_cmds = [f"sudo mkdir -p {cfg['export_root']}"]
    for body in (cfg.get("users") or {}).values():
        mkdir_cmds.append(f"sudo mkdir -p {body['export_path']}")
        mkdir_cmds.append(f"sudo chmod 0777 {body['export_path']}")
    mk = "\n".join(mkdir_cmds)
    # Use a quoted heredoc on the remote side
    return f"""
set -euo pipefail
{mk}
sudo tee /etc/exports >/dev/null << 'EOF'
{exports}EOF
sudo exportfs -ra
sudo systemctl enable --now nfs-server
sudo exportfs -v
"""


def cmd_apply(_: argparse.Namespace) -> int:
    cfg = load_nfs_config()
    proc = ssh_run(apply_script(cfg))
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    return proc.returncode


def cmd_add_user(args: argparse.Namespace) -> int:
    name = args.name
    cfg = load_nfs_config()
    users = cfg.setdefault("users", {})
    if name in users:
        print(f"user {name} already in {CONFIG}")
        return 1
    export_path = f"{cfg['export_root'].rstrip('/')}/{name}"
    users[name] = {"export_path": export_path}
    import yaml as _yaml

    CONFIG.write_text(_yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(f"added {name} -> {export_path}")
    print("run: python nfsctl.py apply")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="115 NFS server control")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("render", help="print /etc/exports content")
    p.set_defaults(func=cmd_render)

    p = sub.add_parser("showmount", help="showmount -e from this machine (no SSH)")
    p.set_defaults(func=cmd_showmount)

    p = sub.add_parser("status", help="SSH 115: exportfs + dirs")
    p.set_defaults(func=cmd_status)

    p = sub.add_parser("apply", help="SSH 115: mkdir + write exports + exportfs -ra")
    p.set_defaults(func=cmd_apply)

    p = sub.add_parser("add-user", help="append user to config/users.yaml")
    p.add_argument("name")
    p.set_defaults(func=cmd_add_user)

    args = parser.parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
