#!/usr/bin/env python3
"""NFS server 管理 CLI。本机运行；apply/status 通过 SSH 落到 115。"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore[assignment]

ROOT = Path(__file__).resolve().parent
CONFIG = ROOT / "config" / "users.yaml"
SERVER_A_GROUPS = ROOT.parent / "serverA" / "config" / "groups.yaml"
CRED_FILE = ROOT.parent / "115ssh"
SYNC_MARKER = "# generated by sync-groups — do not edit by hand"


def load_nfs_config() -> dict:
    if yaml is None:
        raise SystemExit("PyYAML required (use conda env serverA: pip already installed it)")
    with CONFIG.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def allowed_cidrs(cfg: dict) -> list[str]:
    cidrs = cfg.get("allowed_cidrs")
    if cidrs:
        return [str(x) for x in cidrs]
    return [str(cfg["allowed_cidr"])]


def _client_clause(cfg: dict) -> str:
    opts = cfg["mount_options"]
    return " ".join(f"{cidr}({opts})" for cidr in allowed_cidrs(cfg))


def render_exports(cfg: dict) -> str:
    clients = _client_clause(cfg)
    lines = [
        "# generated by 149server/nfsserver/nfsctl.py — do not edit on 115 by hand",
        f"{cfg['export_root']} {clients}",
    ]
    for _name, body in (cfg.get("users") or {}).items():
        lines.append(f"{body['export_path']} {clients}")
    for _name, body in (cfg.get("groups") or {}).items():
        lines.append(f"{body['export_path']} {clients}")
    return "\n".join(lines) + "\n"


def read_ssh_creds() -> tuple[str, str, str]:
    if not CRED_FILE.is_file():
        raise SystemExit(f"missing {CRED_FILE}")
    data: dict[str, str] = {}
    for line in CRED_FILE.read_text(encoding="utf-8").splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        data[key.strip().lower()] = value.strip()
    user = data.get("user") or os.environ.get("NFS_SSH_USER", "kairan")
    host = data.get("ip") or cfg_host_fallback()
    password = data.get("passwd") or os.environ.get("NFS_SSH_PASS", "")
    if not password:
        raise SystemExit("115 ssh password not found (115ssh or NFS_SSH_PASS)")
    return user, host, password


def cfg_host_fallback() -> str:
    try:
        return str(load_nfs_config()["nfs_host"])
    except Exception:
        return "10.250.30.115"


def sshpass_bin() -> str:
    candidate = Path.home() / "miniconda3" / "bin" / "sshpass"
    if candidate.is_file():
        return str(candidate)
    return "sshpass"


def ssh_run(remote: str) -> subprocess.CompletedProcess[str]:
    user, host, password = read_ssh_creds()
    env = os.environ.copy()
    env["SSHPASS"] = password
    cmd = [
        sshpass_bin(),
        "-e",
        "ssh",
        "-o",
        "PreferredAuthentications=password",
        "-o",
        "PubkeyAuthentication=no",
        "-o",
        "StrictHostKeyChecking=accept-new",
        f"{user}@{host}",
        remote,
    ]
    return subprocess.run(cmd, env=env, text=True, capture_output=True, check=False)


def cmd_render(_: argparse.Namespace) -> int:
    sys.stdout.write(render_exports(load_nfs_config()))
    return 0


def cmd_showmount(_: argparse.Namespace) -> int:
    cfg = load_nfs_config()
    proc = subprocess.run(["showmount", "-e", cfg["nfs_host"]], text=True)
    return proc.returncode


def cmd_status(_: argparse.Namespace) -> int:
    proc = ssh_run(
        "echo '=== exportfs -v ==='; sudo exportfs -v; "
        "echo '=== dirs ==='; ls -ld /mnt/dockerContainer/nfs /mnt/dockerContainer/nfs/*; "
        "echo '=== nfs-server ==='; systemctl is-active nfs-server"
    )
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    return proc.returncode


def apply_script(cfg: dict) -> str:
    exports = render_exports(cfg)
    mkdir_cmds = [f"sudo mkdir -p {cfg['export_root']}"]
    for body in (cfg.get("users") or {}).values():
        mkdir_cmds.append(f"sudo mkdir -p {body['export_path']}")
        mkdir_cmds.append(f"sudo chmod 0777 {body['export_path']}")
    for body in (cfg.get("groups") or {}).values():
        mkdir_cmds.append(f"sudo mkdir -p {body['export_path']}")
        mkdir_cmds.append(f"sudo chmod 0777 {body['export_path']}")
    mk = "\n".join(mkdir_cmds)
    # Use a quoted heredoc on the remote side
    return f"""
set -euo pipefail
{mk}
sudo tee /etc/exports >/dev/null << 'EOF'
{exports}EOF
sudo exportfs -ra
sudo systemctl enable --now nfs-server
sudo exportfs -v
"""


def cmd_apply(_: argparse.Namespace) -> int:
    cfg = load_nfs_config()
    proc = ssh_run(apply_script(cfg))
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    return proc.returncode


def _load_server_a_groups() -> dict:
    if not SERVER_A_GROUPS.is_file():
        raise SystemExit(f"missing {SERVER_A_GROUPS}")
    with SERVER_A_GROUPS.open("r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    groups = data.get("groups") or {}
    if not isinstance(groups, dict):
        raise SystemExit(f"invalid groups in {SERVER_A_GROUPS}")
    return groups


def cmd_sync_groups(_: argparse.Namespace) -> int:
    import yaml as _yaml

    groups_src = _load_server_a_groups()
    cfg = load_nfs_config()
    groups_out: dict[str, dict[str, str]] = {}
    for group_id, body in groups_src.items():
        export_path = body["nfs_export_path"]
        groups_out[group_id] = {"export_path": export_path}
    cfg["groups"] = groups_out
    if SYNC_MARKER not in CONFIG.read_text(encoding="utf-8"):
        pass
    text = _yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True)
    if not text.startswith("#"):
        text = f"{SYNC_MARKER}\n{text}"
    CONFIG.write_text(text, encoding="utf-8")
    print(f"synced {len(groups_out)} group(s) from {SERVER_A_GROUPS} -> {CONFIG}")
    for gid, body in groups_out.items():
        print(f"  {gid} -> {body['export_path']}")
    print("run: python nfsctl.py apply")
    return 0


def cmd_add_user(args: argparse.Namespace) -> int:
    name = args.name
    cfg = load_nfs_config()
    users = cfg.setdefault("users", {})
    if name in users:
        print(f"user {name} already in {CONFIG}")
        return 1
    export_path = f"{cfg['export_root'].rstrip('/')}/{name}"
    users[name] = {"export_path": export_path}
    import yaml as _yaml

    CONFIG.write_text(_yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(f"added {name} -> {export_path}")
    print("run: python nfsctl.py apply")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="115 NFS server control")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("render", help="print /etc/exports content")
    p.set_defaults(func=cmd_render)

    p = sub.add_parser("showmount", help="showmount -e from this machine (no SSH)")
    p.set_defaults(func=cmd_showmount)

    p = sub.add_parser("status", help="SSH 115: exportfs + dirs")
    p.set_defaults(func=cmd_status)

    p = sub.add_parser("apply", help="SSH 115: mkdir + write exports + exportfs -ra")
    p.set_defaults(func=cmd_apply)

    p = sub.add_parser("sync-groups", help="sync groups from serverA/config/groups.yaml into nfsserver config")
    p.set_defaults(func=cmd_sync_groups)

    p = sub.add_parser("add-user", help="append user to config/users.yaml")
    p.add_argument("name")
    p.set_defaults(func=cmd_add_user)

    args = parser.parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
