"""Tests for nfsserver nfsctl sync-groups."""

from __future__ import annotations

from pathlib import Path

import yaml

import nfsctl


def test_render_exports_includes_groups(tmp_path: Path, monkeypatch) -> None:
    cfg = {
        "export_root": "/mnt/dockerContainer/nfs",
        "allowed_cidrs": ["10.0.0.0/8"],
        "mount_options": "rw",
        "users": {"alice": {"export_path": "/mnt/dockerContainer/nfs/alice"}},
        "groups": {
            "team-alpha": {"export_path": "/mnt/dockerContainer/nfs/groups/team-alpha"},
        },
    }
    text = nfsctl.render_exports(cfg)
    assert "/mnt/dockerContainer/nfs/groups/team-alpha" in text


def test_sync_groups_writes_nfsserver_config(tmp_path: Path, monkeypatch) -> None:
    server_a_groups = tmp_path / "groups.yaml"
    server_a_groups.write_text(
        """
groups:
  team-alpha:
    nfs_host: "10.250.30.115"
    nfs_export_path: "/mnt/dockerContainer/nfs/groups/team-alpha"
    local_mount_path: "/mnt/nfs/groups/team-alpha"
    members: [alice]
""",
        encoding="utf-8",
    )
    nfs_config = tmp_path / "users.yaml"
    nfs_config.write_text(
        """
nfs_host: "10.250.30.115"
export_root: "/mnt/dockerContainer/nfs"
allowed_cidrs: ["10.0.0.0/8"]
mount_options: "rw"
users:
  alice:
    export_path: "/mnt/dockerContainer/nfs/alice"
""",
        encoding="utf-8",
    )
    monkeypatch.setattr(nfsctl, "SERVER_A_GROUPS", server_a_groups)
    monkeypatch.setattr(nfsctl, "CONFIG", nfs_config)
    monkeypatch.setattr(nfsctl, "SYNC_MARKER", "# generated by sync-groups")

    assert nfsctl.cmd_sync_groups(nfsctl.argparse.Namespace()) == 0
    data = yaml.safe_load(nfs_config.read_text(encoding="utf-8"))
    assert data["groups"]["team-alpha"]["export_path"] == "/mnt/dockerContainer/nfs/groups/team-alpha"
